### ISSUE TITLE
popup seems not working

### ISSUE THREAD

**Issue by byman64** [messi06/vb.net_CefSharp_popup#1]
Please try news.google.com

**Comment by messi06** [comment]
it works just fine, my goal here is to stop the popup from popping lol, so no annoying ads...
double check your code, or try to debug it step by step, see if u r missing some stuff like netframework , c++ etc...
good luck

**Comment by byman64** [comment]
Thx for replay, did u try to open the links on news.google.com?



Il Dom 6 Mag 2018, 20:37 messi06 <notifications@github.com> ha scritto:
